version: '3.9'

services:
  mongodb:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'

  driver-service:
    build: ./driver-service
    env_file:
      - ./driver-service/.env
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    ports:
      - '3001:3000'

  route-service:
    build: ./route-service
    env_file:
      - ./route-service/.env
    depends_on:
      - mongodb
      - rabbitmq
    restart: always
    ports:
      - '3002:3000'

  frontend:
    build: ./frontend
    depends_on:
      - driver-service
      - route-service
    ports:
      - '4200:80'

volumes:
  mongo-data:
