global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'driver-service'
    static_configs:
      - targets: ['driver-service:3000']

  - job_name: 'route-service'
    static_configs:
      - targets: ['route-service:3000']